//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xe.bit.property.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xe.bit.property.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59-15
        ///59-23
        ///59-26
        ///59-3
        ///59-44
        ///47
        ///65
        ///66
        ///67
        ///68
        ///58
        ///59
        ///60
        ///61
        ///62
        ///63
        ///64
        ///13
        ///14
        ///36
        ///48
        ///50
        ///56
        ///88
        ///89
        ///91
        ///94
        ///95
        ///96
        ///97
        ///98
        ///99
        ///100000.
        /// </summary>
        internal static string AreaExceptions {
            get {
                return ResourceManager.GetString("AreaExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map_Id	Map_Label	Parent_id	Parent_Area	NGI_POLYGON_ID	Geo_PolygonID	LOGICAL_GROUPING	MISSING_SHAPE_FILE	Level	Old ΧΕ Area ID
        ///58	Αθήνα &amp; Προάστια	56	Νομός Αττικής		801			2	NO
        ///65	Ανατολική Θεσσαλονίκη	48	Ν. Θεσσαλονίκης		2402			2	NO
        ///60	Βόρεια &amp; Ανατολικά Προάστια	56	Νομός Αττικής		804			2	NO
        ///67	Δυτική Θεσσαλονίκη	48	Ν. Θεσσαλονίκης		2403			2	NO
        ///98	Ηπειρος				L98	Yes		1	NO
        ///97	Θεσσαλία				L97	Yes		1	NO
        ///96	Θράκη				L96	Yes		1	NO
        ///62	Κεντρικά &amp; Δυτικά Προάστια 	56	Νομός Αττικής		806			2	NO
        ///61	Κεντρικά &amp; Ν [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AreaInfo {
            get {
                return ResourceManager.GetString("AreaInfo", resourceCulture);
            }
        }
    }
}
